### PR TITLE
Landing/Marketing Page

### PR DESCRIPTION
**Pull request by Jobsy**
# Description

Describe change or new feature here.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works .
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Omulosi — COMMENTED** [review]
A description for the PR would really help to put everything in context and summarize what you are working on

Also for the desktop view, could you make the page span the entire width, especially the nav bar. Seems kinda awkward to center everything in the mid for a landing page, at least to me.

Otherwise great work, it's nicely styled!

**Review by nobioma1 — CHANGES_REQUESTED** [review]
Nice Job, You could have the header and the footer span out. Also, use the font in the mockup

**Comment by Jobsy** [comment]
Thank you all for the great feedback!

All the necessary changes have been effected.

Kindly review.

Thanks!

**Comment by Jobsy** [comment]
Hi!

Could you kindly check if the bugs have been fixed?

Although, everything looks OK from my end.

**Review by emkayDauda — APPROVED** [review]
Checked the preview website out @Jobsy . It's really awesome. Great Job!

I've just fixed a merge conflict I found laying around in package.json. Didn't particularly add or remove any dependency so it'll still be dandy I imagine. Please check it out and confirm that tho?

Awesome job.

**Pull request merged**
