### PR TITLE
Ft update deck

### PR DESCRIPTION
**Pull request by emkayDauda**
# Description

* Users can now edit an old deck
* Changing deck name or deck tags is now possible

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works .
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by annawinther — DISMISSED** [review]
Super awesome job Maaruf!! Thank you so much 🔥 

Nice job on changing the name when editing a deck as well!
Such good teamwork 💪

**Review by annawinther — DISMISSED** [review]
💪 🔥

**Comment by emkayDauda** [comment]
Sorry for asking you to review again, @annawinther . Hadn't realized the update deck endpoint requests different data from the add deck one.

**Comment by annawinther** [comment]
Thanks @emkayDauda, no problem at all! Sorry I didn't see that either :)

**Review by annawinther — DISMISSED** [review]
Amazing work on fixing the bug, Maaruf! Everything works as expected now 💪 
Thank you!

**Pull request merged**
