### PR TITLE
Ft leaderboard stylings

### PR DESCRIPTION
**Pull request by Jobsy**
# Description

Describe change or new feature here.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works .
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ethaeral — COMMENTED** [review]
The containing div of the cards is a bit big it should be more form fitting.
There should be a bit more space below the line after the heading and the line is really  long 

Other than that great job. You did that really fast. I appreciate it

**Comment by Jobsy** [comment]
@richanynguon issue addressed as stated in your review.
Kindly review it again.

Thank you!

**Review by ethaeral — DISMISSED** [review]
awesome job joba!

**Review by annawinther — COMMENTED** [review]
Really nice job Joba!

It's looking really nice 🔥 
There is a small vertical scroll on the leaderboard component I think, maybe try and see if you can fix that? 
It's such a small thing though!

**Pull request merged**
